return {
	ClaimIntervalSeconds = 24 * 60 * 60,
	SkipProductId = 3708776063,
	Rewards = {
		{
			Type = "Cash",
			Amount = 100,
			ValueText = "$100",
		},
		{
			Type = "Item",
			Rarity = "Epic",
			ValueText = "Epic Item",
		},
		{
			Type = "Cash",
			Amount = 400,
			ValueText = "$400",
		},
		{
			Type = "SaleBoost",
			Percent = 15,
			DurationSeconds = 10 * 60,
			ValueText = "Boost Sell 15%",
		},
		{
			Type = "Cash",
			Amount = 1_000,
			ValueText = "$1,000",
		},
		{
			Type = "Cash",
			Amount = 5_000,
			ValueText = "$5,000",
		},
		{
			Type = "Item",
			Rarity = "Legendary",
			ValueText = "Legendary Item",
		},
	},
}
