return {
	ClaimIntervalSeconds = 24 * 60 * 60,
	SkipProductId = 3708776063,
	Rewards = {
		{
			Type = "Cash",
			Amount = 100,
			ValueText = "$100",
		},
		{
			Type = "Object",
			ObjectKey = "AlarmClock",
			ValueText = "Alarm Clock",
		},
		{
			Type = "Cash",
			Amount = 400,
			ValueText = "$400",
		},
		{
			Type = "SaleBoost",
			Percent = 15,
			DurationSeconds = 10 * 60,
			ValueText = "Boost Sell 15%",
		},
		{
			Type = "Object",
			ObjectKey = "AlarmClock",
			ValueText = "Alarm Clock",
		},
		{
			Type = "Cash",
			Amount = 1_500,
			ValueText = "$1,500",
		},
		{
			Type = "Cash",
			Amount = 5_000,
			ValueText = "$5,000",
		},
	},
}
