return {
	Variation = {
		MinimumPercent = 70,
		MaximumPercent = 130,
	},

	Offer = {
		EmergencyPriceMargin = 0.35,
		EmergencyObject = "AlarmClock",
		TutorialObject = "PhotoFrame",
		TutorialDirtFace = "UiLeft",
	},

	Object = {
		AlarmClock = {
			Name = "Alarm clock",
			MaxValue = 100,
			PriceMinValue = 25,
			PriceMaxValue = 55,
			IdImage = "rbxassetid://131646231048351",
			Rarity = "Common",
			Reputation = 3,
			Rotation = Vector3.new(0, 180, 0),
		},
		PhotoFrame = {
			Name = "Photo frame",
			MaxValue = 100,
			PriceMinValue = 25,
			PriceMaxValue = 55,
			IdImage = "rbxassetid://71206910804350",
			Rarity = "Common",
			Reputation = 3,
			Rotation = Vector3.new(0, 180, 0),
		},
	},
}