return {
	Variation = {
		MinimumPercent = 70,
		MaximumPercent = 130,
	},

	Offer = {
		EmergencyPriceMargin = 0.35,
		TutorialObject = "PhotoFrame",
		TutorialDirtFace = "UiLeft",
	},

	Object = {
		Skateboard = {
			Name = "Skateboard",
			MaxValue = 45,
			PriceMinValue = 0,
			PriceMaxValue = 0,
			IdImage = "rbxassetid://111157604286387",
			Rarity = "Exclusive",
			Reputation = 0,
			Emergency = true,
		},
		OldSuitcase = {
			Name = "Old suitcase",
			MaxValue = 260,
			PriceMinValue = 65,
			PriceMaxValue = 140,
			IdImage = "rbxassetid://102276550411027",
			Rarity = "Uncommon",
			Reputation = 9,
		},
		AlarmClock = {
			Name = "Alarm clock",
			MaxValue = 100,
			PriceMinValue = 25,
			PriceMaxValue = 55,
			IdImage = "rbxassetid://77332415373242",
			Rarity = "Common",
			Reputation = 3,
			Rotation = Vector3.new(0, 180, 0),
		},
		PhotoFrame = {
			Name = "Photo frame",
			MaxValue = 100,
			PriceMinValue = 25,
			PriceMaxValue = 55,
			IdImage = "rbxassetid://78955971518387",
			Rarity = "Common",
			Reputation = 3,
			Rotation = Vector3.new(0, 180, 0),
		},
	},
}
