return {
	Common = {
		Name = "Common",
		Color = Color3.fromRGB(190, 190, 190),
	},

	Uncommon = {
		Name = "Uncommon",
		Color = Color3.fromRGB(90, 210, 110),
	},

	Rare = {
		Name = "Rare",
		Color = Color3.fromRGB(65, 145, 255),
	},

	Epic = {
		Name = "Epic",
		Color = Color3.fromRGB(180, 90, 255),
	},

	Legendary = {
		Name = "Legendary",
		Color = Color3.fromRGB(255, 228, 77),
	},

	Mythic = {
		Name = "Mythic",
		Color = Color3.fromRGB(255, 65, 125),
	},

	Exclusive = {
		Name = "Exclusive",
		Color = Color3.fromRGB(255, 170, 45),
	},
}
