return {
	PriceEstimation = {
		DisplayName = "Price Estimation",
		DefaultLevel = 0,
		DeveloperProductId = 3708293655, 
		CashPriceLevel1 = 200,
	},

	DailyCustomers = {
		DisplayName = "Daily Customers",
		DefaultLevel = 5,
		DeveloperProductId = 3708293711, 
		CashPriceLevel1 = 150,
	},

	PurchaseDiscount = {
		DisplayName = "Purchase Discount",
		MaxPercent = 10,
		DefaultLevel = 0,
		DeveloperProductId = 3708293785, 
		CashPriceLevel1 = 500,
	},
}
